services:
  postgres:
    image: postgres:15
    ports:
      - 0.0.0.0:${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 9
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  default:
    name: cloudbuild
    external: true

volumes:
  postgres-data:
